resource.AddFile("sound/updated/killingsprees/killingspree.mp3")
resource.AddFile("sound/updated/killingsprees/killingfrenzy.mp3")
resource.AddFile("sound/updated/killingsprees/runningriot.mp3")
resource.AddFile("sound/updated/killingsprees/rampage.mp3")
resource.AddFile("sound/updated/killingsprees/untouchable.mp3")
resource.AddFile("sound/updated/killingsprees/invincible.mp3")
resource.AddFile("sound/updated/killingsprees/inconceivable.mp3")
resource.AddFile("sound/updated/killingsprees/unfrigginbelievable.mp3")


resource.AddFile("sound/updated/multikills/doublekill.mp3")
resource.AddFile("sound/updated/multikills/triplekill.mp3")
resource.AddFile("sound/updated/multikills/overkill.mp3")
resource.AddFile("sound/updated/multikills/killtacular.mp3")
resource.AddFile("sound/updated/multikills/killtrocity.mp3")
resource.AddFile("sound/updated/multikills/killimanjaro.mp3")
resource.AddFile("sound/updated/multikills/killtastrophe.mp3")
resource.AddFile("sound/updated/multikills/killpocalypse.mp3")
resource.AddFile("sound/updated/multikills/killionaire.mp3")